### ISSUE TITLE
Suggest to max-width of markdown content

### ISSUE THREAD

**Issue by ldmik** [mjbvz/vscode-github-markdown-preview-style#109]
The suggestion refers to below style:

```css
.github-markdown-content {
    padding: 32px !important;
    max-width: 980px;
    min-width: 200px;
    margin: 0 auto;
}
```
When limited max-width, and you have big mermaid diagram presented, even though you have big screen, you still can't enlarge the picture to enough size.

Suggest to remove the limitation, if no big side effect.
