### ISSUE TITLE
Differences in code blocks: Border Width and the Scrollbar

### ISSUE THREAD

**Issue by Phroneris** [mjbvz/vscode-github-markdown-preview-style#115]
### Description

In the preview provided by this extension, borders and scrollbars of code blocks are different from those on the actual GitHub.

### GitHub's Behavior

Rendering:

```css
.very-long-content {
  content: "very long content very long content very long content very long content very long content very long content very long content very long content very long content very long content";
}
```

Screenshot:

![ext-issue-very-long-content-github](https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/9891867/a3cac788-496e-4334-870b-82cf2b5856c7)

### Extension's Behavior

Screenshot:

![ext-issue-very-long-content-extension](https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/9891867/665c1bfe-37da-4a66-8fae-498bc769922c)

Difference:

- One-pixel wide border
- Scrollbar without buttons at both ends
- Scrollbar hidden under the bottom rounded corners

While the detailed design of the scrollbar is also up to the browser, the border is clearly different at least.

### Specs

- Windows 10 Home 64-bit 22H2
- VS Code 1.82.0
- bierner.github-markdown-preview@0.3.0
- bierner.markdown-preview-github-styles@2.0.2
