### ISSUE TITLE
No white bg in body

### ISSUE THREAD

**Issue by elrumordelaluz** [mjbvz/vscode-github-markdown-preview-style#35]
Is there a reason why after install and activate the _extension_ and opening `Open Webvie Developer Tools`, the `body` is:

```css
body {
  background-color: var(--vscode-editor-background);
  /* ... */
}
```
